ubuntu:
  hosts:
    host-1:
      ansible_host: #.#.#.#
      ansible_port: #
      ansible_ssh_private_key_file: ~/.ssh/your-private-id-file
    host-2:
      ansible_host: #.#.#.#
      ansible_port: #
      ansible_ssh_private_key_file: ~/.ssh/your-private-id-file
  vars:
    ansible_user: ubuntu

debian:
  hosts:
    host-3:
      ansible_host: #.#.#.#
      ansible_ssh_private_key_file: ~/.ssh/your-private-id-file
    localhost:
      ansible_connection: local
  vars:
    ansible_user: debian
    ansible_port: #

debian_based:
  children:
    ubuntu:
    debian:

mikrotiks:
  hosts:
    sw-1:
      ansible_host: #.#.#.#
      ansible_port: #
    sw-2:
      ansible_host: #.#.#.#
      ansible_port: #
  vars:
    ansible_network_os: routeros
    ansible_connection: network_cli
    ansible_user: username
